# Generated by Django 2.2 on 2020-03-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descprition',
            new_name='description',
        ),
    ]
